apiVersion: v1
kind: Pod
metadata:
  name: todo-api
  labels:
    name: todo-api
spec:
  containers:
  - name: todo-api
    image: chandru/node-app
    imagePullPolicy: Never
    ports:
    - containerPort: 3000